#!/usr/bin/bash
# |----------------------------------|
# | Copyright (c) 2024 Vili. GPL-3.0 |
# |----------------------------------|


# Functions
# -----------
# Performs a system update and upgrade.
sys_update() {
    dnf update -y
    dnf upgrade -y
}

# Adds and enables the rpm repos.
add_rpm_repos() {
    dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm -y
    sleep 1
    dnf install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y
    sleep 1
    dnf group update core -y
}

# Adds and enables flathub repos.
add_flatpak_repos() {
    flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
}

# Speeds up dnf.
append_dnf_configs() {
    echo "max_parallel_downloads=10" >> /etc/dnf/dnf.conf
    echo "defaultyes=True" >> /etc/dnf/dnf.conf
    echo "fastestmirror=True" >> /etc/dnf/dnf.conf
    dnf upgrade --refresh -y
}

# Add vscode repo and install vscode
add_vscode() {
    rpm --import https://packages.microsoft.com/keys/microsoft.asc
    sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
    dnf update -y
    dnf install code -y
}

# Add useful developer tools
add_dev_tools() {
    # TODO add more useful tools here...
    # These are the only ones that I personally need
    dnf groupinstall "Development Tools" "Development Libraries" -y
    dnf install kernel-devel python3-pip python3-devel git nodejs nodejs-npm -y
}

# Installs the Nvidia drivers if an Nvidia GPU is detected
needs_nvidia() {
    if lspci | grep -q NVIDIA; then
        echo "Nvidia GPU detected. Do you want to install Nvidia drivers (akmod-nvidia)? (y/N) "
        read -r wants_nvidia
        if [[ $wants_nvidia == "y" || $wants_nvidia == "Y" ]]; then
            dnf install akmod-nvidia -y
            echo "Done!"
        else
            echo "Skipping..."
        fi
    else
        echo "System is not using Nvidia."
    fi
}

# Install user specifed software if any
install_selection() {
    for package in "$@"; do
        dnf install "$package" -y
    done
}

# Install oh-my-zsh
install_oh_my_zsh() {
    dnf install zsh -y
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
}


# Main
# ------------
if [ $(whoami) = "root" ]; then
    echo "FQS (Fedora Quick Start) Script"
    echo
    echo "Finish your post installation steps easily."
    echo
    echo "By Vili (https://vili.dev/)"
    echo
    echo "Do you want to continue with this script? (y/N) "
    read -r input
    if [[ $input == "y" ||  $input == "Y" ]]; then
        echo "Starting with an system update & upgrade..."
        sleep 2
        sys_update
        echo "Done!"
        echo
        echo "Now enabling RPM Fusion repos..."
        sleep 2
        add_rpm_repos
        echo "Done!"
        echo
        echo "Now enabling flathub repos..."
        sleep 2
        add_flatpak_repos
        echo "Done!"
        echo
        echo "Now speeding up dnf..."
        sleep 2
        append_dnf_configs
        echo "Done!"
        echo
        echo "Checking if you are using a Nvidia GPU..."
        sleep 2
        needs_nvidia
        echo
        echo "Do you want to enable vscode repos and install vscode? (y/N)"
        echo
        read -r wants_vscode
        if [[ $wants_vscode == "y" || $wants_vscode == "Y" ]]; then
            add_vscode
            echo "Done!"
        else
            echo "Skipping vscode installation..."
        fi
        echo
        echo "Do you want to install useful development tools? (y/N)"
        echo
        read -r wants_dev_tools
        if [[ $wants_dev_tools == "y" || $wants_dev_tools == "Y" ]]; then
            add_dev_tools
            echo "Done!"
        else
            echo "Skipping devtools installation..."
        fi
        echo
        echo "Do you want to install anything else? (y/N)"
        read -r extra_installs
        if [[ $extra_installs == "y" || $extra_installs == "Y" ]]; then
            echo "Alright, what do you want to intall? (separated by spaces)"
            read -r software
            echo "Installing $software..."
            install_selection $software
            echo "Done!"
            sleep 1
        else
            echo "Skipping optional software installation..."
        fi
        echo
        echo "Lastly, do you want to install oh-my-zsh, for a nicer and better shell?"
        read -r ohmyzsh
        if [[ $ohmyzsh == "y" || $ohmyzsh == "Y" ]]; then
            echo "Installing oh-my-zsh... This is the last step, remember to reboot your system after this!"
            install_oh_my_zsh
            echo "Done!"
        else
            echo "Skipping oh-my-zsh installation..."
        fi
    else
        echo "Cancelled, Goodbye!"
    fi        
else          
    echo "Please run this script as root!"
fi